# Generated by Django 5.2.3 on 2025-06-22 14:26

import django.core.validators
import django.db.models.deletion
import server.app_users.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=150, null=True, validators=[django.core.validators.MinLengthValidator(2, message='First name needs to be at least 2 characters long.'), server.app_users.validators.first_name_validator])),
                ('last_name', models.CharField(blank=True, max_length=150, null=True, validators=[django.core.validators.MinLengthValidator(2, message='Last name needs to be at least 2 characters long.'), server.app_users.validators.last_name_validator])),
                ('gender', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.MinLengthValidator(4, message='Gender needs to be at least 4 characters long.')])),
                ('phone_number', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.MinLengthValidator(10, 'Phone number needs to beexactly 10 characters long.'), server.app_users.validators.phone_number_validator])),
                ('bio', models.TextField(blank=True, max_length=800, null=True, validators=[django.core.validators.MinLengthValidator(10, 'Bio needs to be at least 10 characters long.')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
